
apiVersion: v1
kind: Service
metadata:
  name: moshe-service
  namespace: default
  labels:
    app: nginx-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specifies Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:730335218716:certificate/8f4eeeea-9a1d-443c-a8c8-4de7f8b19aec"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"  # Sets backend protocol to HTTP
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"  # Terminates SSL on port 443
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-02b03655a76056bcd"
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 8080
      targetPort: 80
      protocol: TCP
    - name: "https"
      port: 443
      protocol: TCP
  selector:
    app: nginx-app