apiVersion: v1
kind: ServiceAccount
metadata:
  name: moshe-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::730335218716:role/AmazonEKSLoadBalancerControllerRole
