apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::arn:aws:iam::730335218716:role/moshe-cluster-cluster-20241020191945294000000002
      username: moshe-cluster
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::730335218716:user/moshe-user
      username: moshe-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::arn:aws:iam::730335218716:role/moshe-cluster-cluster-20241020191945294000000002\n  username: moshe-cluster\n  groups:\n    - system:masters\n","mapUsers":"- userarn: arn:aws:iam::730335218716:user/moshe-user\n  username: moshe-user\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2024-10-21T08:07:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "60058"
  uid: 22e0acbb-7ad7-4793-a9bc-869c53caf09c
